
# 1.首先，在workflow文件中定义触发器，例如每次推送到主分支时触发同步操作。
# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 2.添加一个job来执行同步操作。在workflow文件中，添加一个job 并指定使用的操作系统环境。
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    # 在job中添加步骤来执行同步操作。在上述job中，添加步骤来执行skopeo命令，从registry.k8s.io仓库拉取镜像，并将其推送到docker.io仓库。
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
    # 设置项目Secrets以提供Docker Hub登录所需的用户名和密码。
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
    
    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://registry.k8s.io/kube-apiserver:v1.28.3 docker://docker.io/yangxiaolang/kube-apiserver:v1.28.3
        skopeo copy --all docker://registry.k8s.io/kube-controller-manager:v1.28.3 docker://docker.io/yangxiaolang/kube-controller-manager:v1.28.3
        skopeo copy --all docker://registry.k8s.io/kube-scheduler:v1.28.3 docker://docker.io/yangxiaolang/kube-scheduler:v1.28.3
        skopeo copy --all docker://registry.k8s.io/kube-proxy:v1.28.3 docker://docker.io/yangxiaolang/kube-proxy:v1.28.3
        skopeo copy --all docker://registry.k8s.io/coredns/coredns:v1.11.1 docker://docker.io/yangxiaolang/coredns:v1.11.1
        skopeo copy --all docker://registry.k8s.io/pause:3.9 docker://docker.io/yangxiaolang/pause:3.9
        skopeo copy --all docker://registry.k8s.io/etcd:3.5.10-0 docker://docker.io/yangxiaolang/etcd:3.5.10-0
        skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.57.0 docker://yangxiaolang/tektoncd-pipeline-controller:v0.57.0
        skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.57.0 docker://yangxiaolang/tektoncd-pipeline-events:v0.57.0
        skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.57.0 docker://yangxiaolang/tektoncd-pipeline-resolvers:v0.57.0
        skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.57.0 docker://yangxiaolang/tektoncd-pipeline-webhook:v0.57.0
        
